package com.vanillasource.eliot.eliotc.module.fact

import cats.Show
import cats.kernel.Eq
import com.vanillasource.eliot.eliotc.source.content.Sourced

/** A qualifier is a sort-of additional namespace names can live in. It is used as technical namespaces as opposed to
  * user defined ones.
  */
sealed trait Qualifier

object Qualifier {

  /** A name in the "default" namespace, like all "normal" user-defined values.
    */
  case object Default extends Qualifier

  /** Denotes a name that points to a Type constructor.
    */
  case object Type extends Qualifier

  /** Functions belonging to a given ability.
    */
  case class Ability(name: String) extends Qualifier

  /** Function belongs to the given ability implementation.
    *
    * The index disambiguates between multiple implementations of the same ability within one module; the
    * implementation's type pattern is encoded in the signature of the synthetic marker function (the function whose
    * local name equals the ability name) generated by the implement block.
    */
  case class AbilityImplementation(name: Sourced[String], index: Int) extends Qualifier

  /** Renders a qualifier for user-facing messages, dropping source-position noise. In particular an
    * [[AbilityImplementation]] shows just its ability name and index (e.g. `PatternMatch#0`) rather than dumping the
    * whole [[Sourced]] wrapper.
    */
  given Show[Qualifier] with {
    override def show(qualifier: Qualifier): String = qualifier match {
      case Default                            => "Default"
      case Type                               => "Type"
      case Ability(name)                      => name
      case AbilityImplementation(name, index) => s"${name.value}#$index"
    }
  }

  given Eq[Qualifier] = Eq.fromUniversalEquals
}
