package com.vanillasource.eliot.eliotc.apidoc.render

import com.vanillasource.eliot.eliotc.apidoc.model.{DocItem, DocModule}
import com.vanillasource.eliot.eliotc.design.DesignTokens

/** Renders the documentation model to a static HTML site styled with the Eliot brand design system: an `index.html`
  * landing page, one page per module, and a shared `style.css`. The look follows the brand's documentation kit — a
  * light long-form reading surface (`.on-paper`) with a sticky module sidebar, a single signal-green accent, and
  * JetBrains Mono / Inter typography. Code is the hero: every signature and example renders in a dark `ink` well with
  * green-keyword syntax highlighting. Each card shows the highlighted signature, layer/implementation badges, the
  * rendered Markdown documentation, and (for abilities and merged types) nested members and implementations.
  *
  * The stylesheet is the design system's token files (vendored verbatim under `design/`, see that folder's README)
  * followed by apidoc's own component rules, which reference only the semantic tokens — so brand changes flow in by
  * re-syncing the token files, with no Scala edits. The only external assets are the two webfonts (Fontsource CDN,
  * `font-display: swap` with system fallbacks); the site otherwise renders fully offline.
  *
  * Returns the site as `(relativePath, content)` pairs for the caller to write to disk.
  */
object HtmlSite {
  def render(modules: Seq[DocModule]): Seq[(String, String)] = {
    val indexPage =
      "index.html" -> page("Eliot API documentation", renderSidebar(modules, None), indexContent(modules))
    val modulePages =
      modules.map(module => module.fileName -> page(module.title, renderSidebar(modules, Some(module.title)), moduleContent(module)))
    (indexPage +: modulePages) :+ ("style.css" -> css)
  }

  private def escape(text: String): String = EliotHighlighter.escape(text)

  private def page(title: String, sidebar: String, content: String): String =
    s"""<!doctype html>
       |<html lang="en">
       |<head>
       |<meta charset="utf-8">
       |<meta name="viewport" content="width=device-width, initial-scale=1">
       |<title>${escape(title)} · Eliot</title>
       |<link rel="icon" href="${DesignTokens.favicon}">
       |<link rel="stylesheet" href="style.css">
       |</head>
       |<body class="on-paper">
       |<div class="layout">
       |$sidebar
       |<main>$content<footer>Generated by the Eliot apidoc backend.</footer></main>
       |</div>
       |<script>
       |(function(){
       |  var tree=document.getElementById('tree');
       |  if(!tree)return;
       |  var filterMode=false;
       |  // Collapsed-package state lives in the URL (a "#c=a,b" fragment), not localStorage, so it
       |  // survives navigation and refresh even when the site is opened as local file:// pages.
       |  function readSet(){var m=/[#&]c=([^&]*)/.exec(location.hash||''),s=new Set();if(m&&m[1])m[1].split(',').forEach(function(p){if(p)s.add(p);});return s;}
       |  function hashFor(s){return s.size?'#c='+Array.from(s).join(','):'';}
       |  function keyOf(d){return d.parentElement?d.parentElement.getAttribute('data-name'):null;}
       |  function applyOpen(s){
       |    tree.querySelectorAll('details.tree-pkg').forEach(function(d){var k=keyOf(d);d.open=!(k&&s.has(k));});
       |    var a=tree.querySelector('a.active');
       |    if(a){var el=a.parentElement;while(el&&el!==tree){if(el.tagName==='DETAILS')el.open=true;el=el.parentElement;}}
       |  }
       |  function sync(s){
       |    var h=hashFor(s);
       |    document.querySelectorAll('a[href]').forEach(function(a){
       |      var href=a.getAttribute('href');
       |      if(!href||href.charAt(0)==='#'||/^[a-z][a-z0-9+.-]*:/i.test(href))return;
       |      var base=href.split('#')[0];
       |      if(base.slice(-5)==='.html')a.setAttribute('href',base+h);
       |    });
       |    try{history.replaceState(null,'',location.pathname+location.search+h);}catch(e){try{location.hash=h;}catch(e2){}}
       |  }
       |  var current=readSet();
       |  applyOpen(current);
       |  sync(current);
       |  tree.querySelectorAll('details.tree-pkg').forEach(function(d){
       |    var sm=d.querySelector(':scope > summary');
       |    if(!sm)return;
       |    sm.addEventListener('click',function(e){
       |      if(filterMode||e.target.closest('a'))return;
       |      var k=keyOf(d);if(!k)return;
       |      if(d.open)current.add(k);else current.delete(k);
       |      sync(current);
       |    });
       |  });
       |  window.filterModules=function(q){
       |    q=q.trim().toLowerCase();
       |    filterMode=q!=='';
       |    if(!filterMode){tree.querySelectorAll('li').forEach(function(li){li.style.display='';});applyOpen(current);return;}
       |    tree.querySelectorAll('.tree-leaf').forEach(function(li){li.style.display=li.getAttribute('data-name').toLowerCase().indexOf(q)>=0?'':'none';});
       |    [].slice.call(tree.querySelectorAll('li.tree-dir')).reverse().forEach(function(li){
       |      var any=false;
       |      li.querySelectorAll('.tree-leaf').forEach(function(c){if(c.style.display!=='none')any=true;});
       |      li.style.display=any?'':'none';
       |      var d=li.querySelector('details');if(d)d.open=any;
       |    });
       |  };
       |})();
       |</script>
       |</body>
       |</html>
       |""".stripMargin

  /** One node of the sidebar module tree: a single path segment that is either a package (has children), a documented
    * module (has a page), or — rarely — both (a module whose name also prefixes deeper modules).
    */
  private case class TreeNode(segment: String, fullPath: String, module: Option[DocModule], children: Seq[TreeNode])

  /** Groups the modules into a directory tree by their dotted path, packages (directories) before leaf modules, each
    * alphabetical. `active` is the title of the currently-rendered module, highlighted in its page's sidebar.
    */
  private def renderSidebar(modules: Seq[DocModule], active: Option[String]): String = {
    val tree = buildForest(modules.map(m => ((m.name.packages :+ m.name.name).toList, m)), "")
    s"""<nav class="sidebar">
       |<a class="brand" href="index.html">eliot<span class="eliot-cursor"></span><span class="tag">apidoc</span></a>
       |<input class="search" type="search" placeholder="Filter modules…" oninput="filterModules(this.value)" aria-label="Filter modules">
       |<ul class="tree" id="tree">
       |${renderForest(tree, active)}
       |</ul>
       |</nav>""".stripMargin
  }

  private def buildForest(entries: Seq[(List[String], DocModule)], prefix: String): Seq[TreeNode] =
    entries
      .groupBy(_._1.head)
      .toSeq
      .map { case (segment, group) =>
        val path   = if (prefix.isEmpty) segment else s"$prefix.$segment"
        val module = group.collectFirst { case (_ :: Nil, m) => m }
        val deeper = group.collect { case (_ :: rest, m) if rest.nonEmpty => (rest, m) }
        TreeNode(segment, path, module, buildForest(deeper, path))
      }
      .sortBy(node => (node.children.isEmpty, node.segment.toLowerCase))

  private def renderForest(nodes: Seq[TreeNode], active: Option[String]): String =
    nodes.map(renderTreeNode(_, active)).mkString("\n")

  private def renderTreeNode(node: TreeNode, active: Option[String]): String =
    if (node.children.isEmpty)
      node.module match {
        case Some(m) =>
          val cls = if (active.contains(m.title)) """ class="active"""" else ""
          s"""<li class="tree-leaf" data-name="${escape(m.title)}"><a$cls href="${escape(m.fileName)}">${escape(node.segment)}</a></li>"""
        case None    =>
          s"""<li class="tree-leaf" data-name="${escape(node.fullPath)}"><span>${escape(node.segment)}</span></li>"""
      }
    else {
      val summary = node.module match {
        case Some(m) => s"""<a href="${escape(m.fileName)}">${escape(node.segment)}</a>"""
        case None    => escape(node.segment)
      }
      s"""<li class="tree-dir" data-name="${escape(node.fullPath)}"><details class="tree-pkg" open><summary>$summary</summary><ul class="tree">${renderForest(node.children, active)}</ul></details></li>"""
    }

  private def indexContent(modules: Seq[DocModule]): String = {
    val totalItems = modules.map(_.items.size).sum
    val rows = modules
      .map { module =>
        val kinds = module.items.groupBy(_.kind).view.mapValues(_.size)
        val summary = DocItem.Kind.values.toSeq
          .flatMap(k => kinds.get(k).map(n => s"""<span class="count">$n ${escape(k.label)}</span>"""))
          .mkString
        s"""<li><a href="${escape(module.fileName)}">${escape(module.title)}</a>$summary</li>"""
      }
      .mkString("\n")
    s"""<h1>Eliot API documentation</h1>
       |<p class="lead">${modules.size} modules · $totalItems documented definitions. Layers are merged: each name shows its abstract signature together with the platforms that implement it.</p>
       |<ul class="moduleindex">
       |$rows
       |</ul>""".stripMargin
  }

  private def moduleContent(module: DocModule): String = {
    val doc      = module.doc.map(d => s"""<div class="doc">${MarkdownRenderer.render(d)}</div>""").getOrElse("")
    val sections = DocItem.Kind.values.toSeq.flatMap { kind =>
      val items = module.items.filter(_.kind == kind)
      if (items.isEmpty) None
      else Some(s"""<section class="group"><h2 class="group-title">${escape(sectionTitle(kind))}</h2>${items.map(renderItem).mkString}</section>""")
    }
    s"""<h1 class="module-title"><span class="chip chip-module">module</span>${escape(module.title)}</h1>$doc${sections.mkString}"""
  }

  private def sectionTitle(kind: DocItem.Kind): String = kind match {
    case DocItem.Kind.TypeLike => "Types"
    case DocItem.Kind.Ability  => "Abilities"
    case DocItem.Kind.Value    => "Definitions"
  }

  private def renderItem(item: DocItem): String = {
    val badges = badgesFor(item)
    val doc    = item.doc.map(d => s"""<div class="doc">${MarkdownRenderer.render(d)}</div>""").getOrElse("")
    val members =
      if (item.members.isEmpty) ""
      else {
        val label = if (item.kind == DocItem.Kind.Ability) "Methods" else "Definitions"
        val rows  = item.members.map(renderMember).mkString
        s"""<div class="members"><h3>$label</h3>$rows</div>"""
      }
    val implementations =
      if (item.implementations.isEmpty) ""
      else s"""<div class="members"><h3>Implementations</h3>${item.implementations.map(renderImplementation).mkString}</div>"""

    s"""<section class="item item-${item.kind.toString.toLowerCase}" id="${escape(item.anchor)}">
       |<div class="item-head"><span class="chip chip-${item.kind.toString.toLowerCase}">${escape(item.kind.label)}</span><h2 class="item-name"><a href="#${escape(item.anchor)}">${escape(item.name)}</a></h2>$badges</div>
       |<pre class="sig"><code>${EliotHighlighter.highlight(item.signature)}</code></pre>
       |$doc$members$implementations
       |</section>""".stripMargin
  }

  private def renderMember(member: DocItem.Member): String = {
    val layer = member.layer.map(l => s"""<span class="badge badge-layer">${escape(l)}</span>""").getOrElse("")
    val doc   = member.doc.map(d => s"""<div class="doc">${MarkdownRenderer.render(d)}</div>""").getOrElse("")
    s"""<div class="member"><div class="member-sig"><pre class="sig"><code>${EliotHighlighter.highlight(member.signature)}</code></pre>$layer</div>$doc</div>"""
  }

  private def renderImplementation(impl: DocItem.Implementation): String = {
    val layers = impl.layers.map(l => s"""<span class="badge badge-layer">${escape(l)}</span>""").mkString
    val doc    = impl.doc.map(d => s"""<div class="doc">${MarkdownRenderer.render(d)}</div>""").getOrElse("")
    s"""<div class="member"><div class="member-sig"><pre class="sig"><code>${EliotHighlighter.highlight(impl.signature)}</code></pre>$layers</div>$doc</div>"""
  }

  private def badgesFor(item: DocItem): String = {
    val implemented =
      if (item.implementedOn.nonEmpty)
        item.implementedOn.map(l => s"""<span class="badge badge-impl" title="implemented on $l">$l</span>""").mkString
      else if (item.kind != DocItem.Kind.Ability) """<span class="badge badge-abstract">abstract</span>"""
      else ""
    s"""<span class="badges">$implemented</span>"""
  }

  /** The full stylesheet: the shared Eliot Design System token layer, followed by apidoc's component rules. A `def`
    * (not a `val`) so it never observes the `components` val before its in-order initialization.
    */
  private def css: String =
    s"""${DesignTokens.tokensCss}
       |
       |/* ======================================================================
       | * apidoc components — reference only the semantic tokens defined above,
       | * so a brand change flows in by re-syncing the shared tokens (no edits
       | * here). Code wells deliberately use the fixed dark base palette
       | * (--ink/--paper/--line/--syn-*) so code stays dark and is the hero.
       | * ====================================================================== */
       |$components""".stripMargin

  private val components: String =
    """.layout{display:flex;align-items:flex-start}
      |.sidebar{position:sticky;top:0;height:100vh;width:280px;flex:0 0 280px;overflow-y:auto;border-right:1px solid var(--border);padding:22px 16px;background:var(--bg)}
      |.sidebar::-webkit-scrollbar{width:9px}
      |.sidebar::-webkit-scrollbar-thumb{background:var(--border-strong);border-radius:var(--radius-sm);border:2px solid var(--bg)}
      |.sidebar::-webkit-scrollbar-track{background:transparent}
      |.brand{display:inline-flex;align-items:center;gap:6px;font-family:var(--font-display);font-weight:var(--weight-medium);font-size:1.2rem;color:var(--text);margin:2px 4px 20px;letter-spacing:var(--tracking-tight)}
      |.brand:hover{text-decoration:none}
      |.brand .eliot-cursor{vertical-align:baseline}
      |.brand .tag{color:var(--text-muted);font-weight:var(--weight-regular);font-size:.62rem;letter-spacing:var(--tracking-label);text-transform:uppercase;margin-left:2px}
      |.search{width:100%;padding:8px 12px;border:1px solid var(--border);border-radius:var(--radius-sm);font-size:var(--text-sm);font-family:var(--font-body);margin-bottom:16px;background:var(--surface);color:var(--text);transition:border-color var(--dur) var(--ease),box-shadow var(--dur) var(--ease)}
      |.search::placeholder{color:var(--text-faint)}
      |.search:focus{outline:none;border-color:var(--accent);box-shadow:0 0 0 3px var(--accent-wash)}
      |.tree{list-style:none;margin:0;padding:0}
      |.tree .tree{margin:0 0 0 12px;padding:0;border-left:1px solid var(--border)}
      |.tree-leaf a,.tree-leaf span,.tree-pkg>summary{display:flex;align-items:center;gap:8px;padding:5px 10px;border-radius:var(--radius-xs);font-size:var(--text-sm);line-height:1.3;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;border-left:2px solid transparent;margin-left:-2px;transition:background var(--dur-fast) var(--ease),color var(--dur-fast) var(--ease)}
      |.tree-leaf a,.tree-leaf span{color:var(--text-muted);font-weight:var(--weight-regular);font-family:var(--font-body)}
      |.tree-leaf a:hover{background:var(--surface-sunken);color:var(--text);text-decoration:none}
      |.tree-leaf a.active{color:var(--green-dim);border-left-color:var(--accent);background:var(--surface-sunken);font-weight:var(--weight-medium)}
      |.tree-pkg>summary{cursor:pointer;list-style:none;color:var(--text);font-weight:var(--weight-medium);font-family:var(--font-display);font-size:.82rem}
      |.tree-pkg>summary::-webkit-details-marker{display:none}
      |.tree-pkg>summary::before{content:"";flex:0 0 auto;width:0;height:0;border-style:solid;border-width:3.5px 0 3.5px 6px;border-color:transparent transparent transparent var(--text-muted);transition:transform var(--dur) var(--ease);transform-origin:3px center}
      |.tree-pkg[open]>summary::before{transform:rotate(90deg)}
      |.tree-pkg>summary:hover{background:var(--surface-sunken)}
      |.tree-pkg>summary a{color:inherit;padding:0;margin:0;border:0;background:none;flex:1 1 auto;overflow:hidden;text-overflow:ellipsis;font-weight:inherit;font-family:inherit}
      |main{flex:1 1 auto;max-width:880px;padding:40px 48px 64px;min-width:0}
      |h1{font-size:var(--text-h1);margin:0 0 16px;color:var(--text)}
      |.module-title{display:flex;align-items:center;gap:12px;font-size:var(--text-h2)}
      |.lead{font-family:var(--font-body);color:var(--text-muted);font-size:var(--text-body-lg);line-height:var(--leading-normal);margin:0 0 32px;max-width:680px}
      |.moduleindex{list-style:none;margin:0;padding:0}
      |.moduleindex li{display:flex;align-items:center;gap:10px;padding:10px 2px;border-bottom:1px solid var(--border)}
      |.moduleindex a{font-family:var(--font-display);font-weight:var(--weight-medium);font-size:.95rem;color:var(--green-dim)}
      |.count{color:var(--text-muted);font-size:var(--text-xs);font-family:var(--font-code);background:var(--surface-sunken);border:1px solid var(--border);border-radius:var(--radius-sm);padding:1px 8px}
      |.group{margin:40px 0}
      |.group-title{font-family:var(--font-display);font-size:var(--text-xs);font-weight:var(--weight-medium);text-transform:uppercase;letter-spacing:.06em;color:var(--text-muted);border-bottom:1px solid var(--border);padding-bottom:8px;margin:0 0 4px}
      |.item{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius-md);padding:18px 20px;margin:16px 0;transition:border-color var(--dur) var(--ease)}
      |.item:hover{border-color:var(--border-strong)}
      |.item-head{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin-bottom:10px}
      |.item-name{font-size:var(--text-h4);margin:0;font-family:var(--font-display);font-weight:var(--weight-medium)}
      |.item-name a{color:var(--text)}
      |.item-name a:hover{color:var(--green-dim);text-decoration:none}
      |.chip{font-family:var(--font-code);font-size:.66rem;text-transform:uppercase;letter-spacing:.06em;font-weight:var(--weight-medium);color:var(--text-muted);background:var(--surface-sunken);border:1px solid var(--border);border-radius:var(--radius-xs);padding:2px 7px}
      |.chip-module{color:var(--green-dim);background:var(--accent-wash);border-color:var(--accent-line)}
      |.badges{margin-left:auto;display:flex;gap:6px;flex-wrap:wrap}
      |.badge{font-family:var(--font-code);font-size:.7rem;border-radius:var(--radius-sm);padding:2px 8px;border:1px solid var(--border);color:var(--text-muted);background:var(--surface)}
      |.badge-impl{background:var(--accent-wash);color:var(--green-dim);border-color:var(--accent-line)}
      |.badge-abstract{background:var(--surface-sunken);color:var(--text-muted);border:1px dashed var(--border-strong)}
      |.badge-layer{background:var(--surface-sunken);color:var(--text-muted)}
      |pre.sig{background:var(--ink);color:var(--paper);border:1px solid var(--line);border-radius:var(--radius-md);padding:12px 14px;overflow-x:auto;margin:0;font-size:.875rem;line-height:var(--leading-code)}
      |.doc{margin:12px 0 2px;font-family:var(--font-body)}
      |.doc p{margin:.6em 0;line-height:var(--leading-normal)}
      |.doc a{color:var(--green-dim);border-bottom:1px solid var(--accent-line)}
      |.doc a:hover{border-bottom-color:var(--accent);text-decoration:none}
      |.doc pre.code{background:var(--ink);color:var(--paper);border:1px solid var(--line);border-radius:var(--radius-md);padding:14px 16px;overflow-x:auto;font-size:.86rem;line-height:var(--leading-code);margin:16px 0}
      |.doc code{font-family:var(--font-code);background:var(--surface-sunken);border:1px solid var(--border);border-radius:var(--radius-xs);padding:.08em .35em;font-size:.86em;color:var(--text)}
      |.doc pre.code code{background:none;border:0;padding:0;color:inherit}
      |.members{margin:14px 0 2px;padding-left:16px;border-left:2px solid var(--border)}
      |.members h3{font-family:var(--font-display);font-size:.72rem;color:var(--text-muted);margin:10px 0 8px;text-transform:uppercase;letter-spacing:.05em;font-weight:var(--weight-medium)}
      |.member{margin:10px 0}
      |.member-sig{display:flex;align-items:center;gap:8px;flex-wrap:wrap}
      |.member-sig pre.sig{flex:1 1 auto}
      |footer{margin-top:56px;padding-top:18px;border-top:1px solid var(--border);color:var(--text-faint);font-size:.8rem;font-family:var(--font-code)}
      |.kw{color:var(--syn-keyword);font-weight:var(--weight-medium)}
      |.ty{color:var(--syn-type)}
      |.fn{color:var(--syn-fn)}
      |.num{color:var(--syn-number)}
      |.str{color:var(--syn-string)}
      |.cm{color:var(--syn-comment);font-style:italic}
      |.op{color:var(--syn-punct)}
      |@media(max-width:820px){.sidebar{display:none}main{padding:24px 20px}}
      |""".stripMargin
}
