package com.vanillasource.eliot.eliotc.apidoc.render

import com.vanillasource.eliot.eliotc.apidoc.model.{DocItem, DocModule}

/** Renders the documentation model to a self-contained static HTML site: an `index.html` landing page, one page per
  * module, and a shared `style.css`. The look borrows from rustdoc/ExDoc — a sticky module sidebar with client-side
  * filtering, and one card per documented item showing a syntax-highlighted signature, layer/implementation badges, the
  * rendered Markdown documentation, and (for abilities and merged types) nested members and implementations.
  *
  * Returns the site as `(relativePath, content)` pairs for the caller to write to disk. No assets are external.
  */
object HtmlSite {
  def render(modules: Seq[DocModule]): Seq[(String, String)] = {
    val indexPage =
      "index.html" -> page("Eliot API documentation", renderSidebar(modules, None), indexContent(modules))
    val modulePages =
      modules.map(module => module.fileName -> page(module.title, renderSidebar(modules, Some(module.title)), moduleContent(module)))
    (indexPage +: modulePages) :+ ("style.css" -> css)
  }

  private def escape(text: String): String = EliotHighlighter.escape(text)

  private def page(title: String, sidebar: String, content: String): String =
    s"""<!doctype html>
       |<html lang="en">
       |<head>
       |<meta charset="utf-8">
       |<meta name="viewport" content="width=device-width, initial-scale=1">
       |<title>${escape(title)} · Eliot</title>
       |<link rel="stylesheet" href="style.css">
       |</head>
       |<body>
       |<div class="layout">
       |$sidebar
       |<main>$content<footer>Generated by the Eliot apidoc backend.</footer></main>
       |</div>
       |<script>
       |(function(){
       |  var KEY='eliot-apidoc-tree';
       |  var tree=document.getElementById('tree');
       |  var filterMode=false;
       |  function load(){try{return JSON.parse(localStorage.getItem(KEY))||{};}catch(e){return {};}}
       |  function save(s){try{localStorage.setItem(KEY,JSON.stringify(s));}catch(e){}}
       |  function keyOf(d){return d.parentElement?d.parentElement.getAttribute('data-name'):null;}
       |  function applyState(){
       |    var st=load();
       |    tree.querySelectorAll('details.tree-pkg').forEach(function(d){
       |      var k=keyOf(d);d.open=(k&&Object.prototype.hasOwnProperty.call(st,k))?!!st[k]:true;
       |    });
       |    var active=tree.querySelector('a.active');
       |    if(active){var el=active.parentElement;while(el&&el!==tree){if(el.tagName==='DETAILS')el.open=true;el=el.parentElement;}}
       |  }
       |  window.filterModules=function(q){
       |    q=q.trim().toLowerCase();
       |    filterMode=q!=='';
       |    if(!filterMode){tree.querySelectorAll('li').forEach(function(li){li.style.display='';});applyState();return;}
       |    tree.querySelectorAll('.tree-leaf').forEach(function(li){
       |      li.style.display=li.getAttribute('data-name').toLowerCase().indexOf(q)>=0?'':'none';
       |    });
       |    Array.prototype.slice.call(tree.querySelectorAll('li.tree-dir')).reverse().forEach(function(li){
       |      var any=false;
       |      li.querySelectorAll('.tree-leaf').forEach(function(c){if(c.style.display!=='none')any=true;});
       |      li.style.display=any?'':'none';
       |      var d=li.querySelector('details');if(d)d.open=any;
       |    });
       |  };
       |  if(tree){
       |    applyState();
       |    tree.querySelectorAll('details.tree-pkg').forEach(function(d){
       |      d.addEventListener('toggle',function(){
       |        if(filterMode)return;
       |        var st=load(),k=keyOf(d);if(k){st[k]=d.open;save(st);}
       |      });
       |    });
       |  }
       |})();
       |</script>
       |</body>
       |</html>
       |""".stripMargin

  /** One node of the sidebar module tree: a single path segment that is either a package (has children), a documented
    * module (has a page), or — rarely — both (a module whose name also prefixes deeper modules).
    */
  private case class TreeNode(segment: String, fullPath: String, module: Option[DocModule], children: Seq[TreeNode])

  /** Groups the modules into a directory tree by their dotted path, packages (directories) before leaf modules, each
    * alphabetical. `active` is the title of the currently-rendered module, highlighted in its page's sidebar.
    */
  private def renderSidebar(modules: Seq[DocModule], active: Option[String]): String = {
    val tree = buildForest(modules.map(m => ((m.name.packages :+ m.name.name).toList, m)), "")
    s"""<nav class="sidebar">
       |<a class="brand" href="index.html">Eliot<span>apidoc</span></a>
       |<input class="search" type="search" placeholder="Filter modules…" oninput="filterModules(this.value)" aria-label="Filter modules">
       |<ul class="tree" id="tree">
       |${renderForest(tree, active)}
       |</ul>
       |</nav>""".stripMargin
  }

  private def buildForest(entries: Seq[(List[String], DocModule)], prefix: String): Seq[TreeNode] =
    entries
      .groupBy(_._1.head)
      .toSeq
      .map { case (segment, group) =>
        val path   = if (prefix.isEmpty) segment else s"$prefix.$segment"
        val module = group.collectFirst { case (_ :: Nil, m) => m }
        val deeper = group.collect { case (_ :: rest, m) if rest.nonEmpty => (rest, m) }
        TreeNode(segment, path, module, buildForest(deeper, path))
      }
      .sortBy(node => (node.children.isEmpty, node.segment.toLowerCase))

  private def renderForest(nodes: Seq[TreeNode], active: Option[String]): String =
    nodes.map(renderTreeNode(_, active)).mkString("\n")

  private def renderTreeNode(node: TreeNode, active: Option[String]): String =
    if (node.children.isEmpty)
      node.module match {
        case Some(m) =>
          val cls = if (active.contains(m.title)) """ class="active"""" else ""
          s"""<li class="tree-leaf" data-name="${escape(m.title)}"><a$cls href="${escape(m.fileName)}">${escape(node.segment)}</a></li>"""
        case None    =>
          s"""<li class="tree-leaf" data-name="${escape(node.fullPath)}"><span>${escape(node.segment)}</span></li>"""
      }
    else {
      val summary = node.module match {
        case Some(m) => s"""<a href="${escape(m.fileName)}">${escape(node.segment)}</a>"""
        case None    => escape(node.segment)
      }
      s"""<li class="tree-dir" data-name="${escape(node.fullPath)}"><details class="tree-pkg" open><summary>$summary</summary><ul class="tree">${renderForest(node.children, active)}</ul></details></li>"""
    }

  private def indexContent(modules: Seq[DocModule]): String = {
    val totalItems = modules.map(_.items.size).sum
    val rows = modules
      .map { module =>
        val kinds = module.items.groupBy(_.kind).view.mapValues(_.size)
        val summary = DocItem.Kind.values.toSeq
          .flatMap(k => kinds.get(k).map(n => s"""<span class="count">$n ${escape(k.label)}</span>"""))
          .mkString
        s"""<li><a href="${escape(module.fileName)}">${escape(module.title)}</a>$summary</li>"""
      }
      .mkString("\n")
    s"""<h1>Eliot API documentation</h1>
       |<p class="lead">${modules.size} modules · $totalItems documented definitions. Layers are merged: each name shows its abstract signature together with the platforms that implement it.</p>
       |<ul class="moduleindex">
       |$rows
       |</ul>""".stripMargin
  }

  private def moduleContent(module: DocModule): String = {
    val doc      = module.doc.map(d => s"""<div class="doc">${MarkdownRenderer.render(d)}</div>""").getOrElse("")
    val sections = DocItem.Kind.values.toSeq.flatMap { kind =>
      val items = module.items.filter(_.kind == kind)
      if (items.isEmpty) None
      else Some(s"""<section class="group"><h2 class="group-title">${escape(sectionTitle(kind))}</h2>${items.map(renderItem).mkString}</section>""")
    }
    s"""<h1 class="module-title"><span class="chip chip-module">module</span>${escape(module.title)}</h1>$doc${sections.mkString}"""
  }

  private def sectionTitle(kind: DocItem.Kind): String = kind match {
    case DocItem.Kind.TypeLike => "Types"
    case DocItem.Kind.Ability  => "Abilities"
    case DocItem.Kind.Value    => "Definitions"
  }

  private def renderItem(item: DocItem): String = {
    val badges = badgesFor(item)
    val doc    = item.doc.map(d => s"""<div class="doc">${MarkdownRenderer.render(d)}</div>""").getOrElse("")
    val members =
      if (item.members.isEmpty) ""
      else {
        val label = if (item.kind == DocItem.Kind.Ability) "Methods" else "Definitions"
        val rows  = item.members.map(renderMember).mkString
        s"""<div class="members"><h3>$label</h3>$rows</div>"""
      }
    val implementations =
      if (item.implementations.isEmpty) ""
      else s"""<div class="members"><h3>Implementations</h3>${item.implementations.map(renderImplementation).mkString}</div>"""

    s"""<section class="item item-${item.kind.toString.toLowerCase}" id="${escape(item.anchor)}">
       |<div class="item-head"><span class="chip chip-${item.kind.toString.toLowerCase}">${escape(item.kind.label)}</span><h2 class="item-name"><a href="#${escape(item.anchor)}">${escape(item.name)}</a></h2>$badges</div>
       |<pre class="sig"><code>${EliotHighlighter.highlight(item.signature)}</code></pre>
       |$doc$members$implementations
       |</section>""".stripMargin
  }

  private def renderMember(member: DocItem.Member): String = {
    val layer = member.layer.map(l => s"""<span class="badge badge-layer">${escape(l)}</span>""").getOrElse("")
    val doc   = member.doc.map(d => s"""<div class="doc">${MarkdownRenderer.render(d)}</div>""").getOrElse("")
    s"""<div class="member"><div class="member-sig"><pre class="sig"><code>${EliotHighlighter.highlight(member.signature)}</code></pre>$layer</div>$doc</div>"""
  }

  private def renderImplementation(impl: DocItem.Implementation): String = {
    val layers = impl.layers.map(l => s"""<span class="badge badge-layer">${escape(l)}</span>""").mkString
    val doc    = impl.doc.map(d => s"""<div class="doc">${MarkdownRenderer.render(d)}</div>""").getOrElse("")
    s"""<div class="member"><div class="member-sig"><pre class="sig"><code>${EliotHighlighter.highlight(impl.signature)}</code></pre>$layers</div>$doc</div>"""
  }

  private def badgesFor(item: DocItem): String = {
    val implemented =
      if (item.implementedOn.nonEmpty)
        item.implementedOn.map(l => s"""<span class="badge badge-impl" title="implemented on $l">$l</span>""").mkString
      else if (item.kind != DocItem.Kind.Ability) """<span class="badge badge-abstract">abstract</span>"""
      else ""
    s"""<span class="badges">$implemented</span>"""
  }

  private val css: String =
    """:root{
      |  --bg:#fbfbfd; --fg:#1d1d22; --muted:#6b6b78; --line:#e6e6ee; --card:#ffffff; --hover:#f0f0fa;
      |  --accent:#5b56e0; --kw:#9326c9; --ty:#1a8a7a; --fn:#2d6cdf; --num:#b5640a; --str:#1f8a3b; --cm:#8a8a96; --op:#54545f;
      |  --chip-type:#1a8a7a; --chip-ability:#9326c9; --chip-value:#2d6cdf; --chip-module:#6b6b78;
      |}
      |*{box-sizing:border-box}
      |html{font-size:15px}
      |body{margin:0;background:var(--bg);color:var(--fg);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;line-height:1.55}
      |code,pre,.sig{font-family:"JetBrains Mono",ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}
      |a{color:var(--accent);text-decoration:none}
      |a:hover{text-decoration:underline}
      |.layout{display:flex;align-items:flex-start}
      |.sidebar{position:sticky;top:0;height:100vh;width:280px;flex:0 0 280px;overflow-y:auto;border-right:1px solid var(--line);padding:18px 14px;background:#fcfcfe}
      |.sidebar::-webkit-scrollbar{width:9px}
      |.sidebar::-webkit-scrollbar-thumb{background:#dadae6;border-radius:5px;border:2px solid #fcfcfe}
      |.sidebar:hover::-webkit-scrollbar-thumb{background:#c8c8d8}
      |.sidebar::-webkit-scrollbar-track{background:transparent}
      |.brand{display:block;font-weight:700;font-size:1.3rem;color:var(--fg);margin-bottom:14px}
      |.brand span{color:var(--accent);font-weight:600;font-size:.8rem;margin-left:6px;vertical-align:middle}
      |.search{width:100%;padding:8px 11px;border:1px solid var(--line);border-radius:8px;font-size:.875rem;margin-bottom:14px;background:#fff;transition:border-color .12s ease,box-shadow .12s ease}
      |.search:focus{outline:none;border-color:var(--accent);box-shadow:0 0 0 3px rgba(91,86,224,.15)}
      |.tree{list-style:none;margin:0;padding:0}
      |.tree .tree{margin:0 0 0 12px;padding:0;border-left:1px solid var(--line)}
      |.tree-leaf a,.tree-leaf span,.tree-pkg>summary{display:flex;align-items:center;gap:8px;padding:5px 9px;border-radius:7px;font-size:.875rem;line-height:1.3;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;transition:background .1s ease,color .1s ease}
      |.tree-leaf a,.tree-leaf span{color:#55555f;font-weight:400}
      |.tree-leaf a::before,.tree-leaf span::before{content:"";flex:0 0 auto;width:6px;height:6px}
      |.tree-leaf a:hover{background:var(--hover);color:var(--fg);text-decoration:none}
      |.tree-leaf a.active{background:var(--accent);color:#fff;font-weight:600;box-shadow:0 1px 3px rgba(91,86,224,.35)}
      |.tree-pkg>summary{cursor:pointer;list-style:none;color:var(--fg);font-weight:700}
      |.tree-pkg>summary::-webkit-details-marker{display:none}
      |.tree-pkg>summary::before{content:"";flex:0 0 auto;width:0;height:0;border-style:solid;border-width:4px 0 4px 6px;border-color:transparent transparent transparent var(--fg);transition:transform .15s ease;transform-origin:3px center}
      |.tree-pkg[open]>summary::before{transform:rotate(90deg)}
      |.tree-pkg>summary:hover{background:var(--hover)}
      |.tree-pkg>summary a{color:inherit;padding:0;background:none;flex:1 1 auto;overflow:hidden;text-overflow:ellipsis;font-weight:inherit}
      |main{flex:1 1 auto;max-width:920px;padding:34px 44px;min-width:0}
      |h1{font-size:1.9rem;margin:0 0 18px;font-weight:700}
      |.module-title{display:flex;align-items:center;gap:12px;font-family:ui-monospace,monospace}
      |.lead{color:var(--muted);font-size:1.02rem;margin-bottom:26px}
      |.moduleindex{list-style:none;margin:0;padding:0}
      |.moduleindex li{display:flex;align-items:center;gap:10px;padding:7px 0;border-bottom:1px solid var(--line)}
      |.moduleindex a{font-family:ui-monospace,monospace;font-weight:600}
      |.count{color:var(--muted);font-size:.78rem;background:#f2f2f7;border-radius:20px;padding:1px 9px}
      |.group{margin:34px 0}
      |.group-title{font-size:1.15rem;border-bottom:2px solid var(--line);padding-bottom:6px;margin-bottom:6px;font-weight:700}
      |.item{background:var(--card);border:1px solid var(--line);border-left:3px solid var(--line);border-radius:10px;padding:16px 18px;margin:16px 0}
      |.item-typelike{border-left-color:var(--chip-type)}
      |.item-ability{border-left-color:var(--chip-ability)}
      |.item-value{border-left-color:var(--chip-value)}
      |.item-head{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin-bottom:8px}
      |.item-name{font-size:1.15rem;margin:0;font-family:ui-monospace,monospace}
      |.item-name a{color:var(--fg)}
      |.chip{font-size:.7rem;text-transform:uppercase;letter-spacing:.04em;font-weight:700;color:#fff;border-radius:5px;padding:2px 7px}
      |.chip-typelike,.chip-type{background:var(--chip-type)}
      |.chip-ability{background:var(--chip-ability)}
      |.chip-value{background:var(--chip-value)}
      |.chip-module{background:var(--chip-module)}
      |.badges{margin-left:auto;display:flex;gap:5px;flex-wrap:wrap}
      |.badge{font-size:.72rem;border-radius:5px;padding:2px 7px;border:1px solid var(--line)}
      |.badge-impl{background:#e9f7ee;color:#1f8a3b;border-color:#bfe6cd}
      |.badge-abstract{background:#f3f0fd;color:#7a3fc4;border-color:#ddd2f5}
      |.badge-layer{background:#f2f2f7;color:var(--muted)}
      |pre.sig{background:#f7f7fb;border:1px solid var(--line);border-radius:8px;padding:10px 12px;overflow-x:auto;margin:0;font-size:.9rem}
      |.doc{margin:10px 0 2px}
      |.doc p{margin:.5em 0}
      |.doc pre.code{background:#eef0fa;color:var(--fg);border:1px solid #dcdcf0;border-left:3px solid var(--accent);border-radius:8px;padding:12px 14px;overflow-x:auto;font-size:.86rem}
      |.doc code{background:#f2f2f7;border-radius:4px;padding:.1em .35em;font-size:.88em}
      |.doc pre.code code{background:none;padding:0}
      |.members{margin:12px 0 2px;padding-left:14px;border-left:2px solid var(--line)}
      |.members h3{font-size:.95rem;color:var(--muted);margin:8px 0 6px;text-transform:uppercase;letter-spacing:.03em}
      |.member{margin:8px 0}
      |.member-sig{display:flex;align-items:center;gap:8px;flex-wrap:wrap}
      |.member-sig pre.sig{flex:1 1 auto}
      |footer{margin-top:50px;padding-top:16px;border-top:1px solid var(--line);color:var(--muted);font-size:.82rem}
      |.kw{color:var(--kw);font-weight:600}
      |.ty{color:var(--ty)}
      |.fn{color:var(--fn)}
      |.num{color:var(--num)}
      |.str{color:var(--str)}
      |.cm{color:var(--cm);font-style:italic}
      |.op{color:var(--op)}
      |@media(max-width:760px){.sidebar{display:none}main{padding:20px}}
      |""".stripMargin
}
