name:                eliotc
version:             0.1.0.0
github:              "robertbraeutigam/eliot"
license:             BSD3
author:              "Robert Brautigam"
maintainer:          "brautigam.robert.gyula@gmail.com"
copyright:           "Robert Brautigam"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Compiler for the ELIOT Programming Language
category:            Compiler

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/robertbraeutigam/eliot#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- cmdargs
- ansi-terminal
- directory
- filepath
- stm
- parsec
- hashable
- extra
- transformers
- lifted-base
- ttrie
- lifted-async
- utility-ht

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  eliotc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - eliotc

tests:
  eliotc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - eliotc
