package com.vanillasource.eliot.eliotc.jvm.classgen.fact

import java.util.Arrays

/** One generated class file: its name and its bytecode.
  *
  * Equality is **by content**, not by array reference. Default case-class equality compares `bytecode` with `eq`, so
  * every `GeneratedModule` compares unequal to a restored copy of itself — the cache's equality-stability invariant
  * (`docs/incremental-compilation.md` §2: `read(write(v)) == recompute(v)`) fails, and §4 measured all 26 of them
  * unstable for exactly this reason, leaving generated bytecode drillable but never acceptable from cache. Comparing
  * the bytes is what makes it cacheable, and it is sound because code generation is deterministic: the same inputs
  * produce the same bytes (the same property the byte-identity build guard already relies on).
  */
case class ClassFile(fileName: String, bytecode: Array[Byte]) {
  override def equals(other: Any): Boolean = other match {
    case that: ClassFile => fileName == that.fileName && Arrays.equals(bytecode, that.bytecode)
    case _               => false
  }

  override def hashCode(): Int = 31 * fileName.hashCode + Arrays.hashCode(bytecode)
}
